### ISSUE TITLE
Create a binary distribution

### ISSUE THREAD

**Issue by neurocyte** [neurocyte/ghc-android#15]
Building the full cross compiler with template-haskell support takes quite a while because it is in effect a stage 3 compiler. I think a binary distribution would really help lower the barrier to entry for Haskell based Android development.

Would anyone else use a binary distribution?

**Comment by nerdRenegade** [comment]
Any progress on this? Im trying to buld under gnuroot on android... Eventually we should see the Haskell platform targeting android, but maybe we will have to write it...
